version: "3.7"

services:
  node_app:
    deploy:
      replicas: 4
      update_config: # update the service configuration when the image is updated in the registry or the service's configuration is changed
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
        delay: 5s

    build:
      context: .
    image: node_app

    env_file:
      - ./.env
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    restart: always
    volumes:
      - postgres-db:/var/lib/postgresql/data
    container_name: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=example
    ports:
      - "5432:5432"

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo_db:27017/
  #   depends_on:
  #     - mongo_db

  redis:
    image: redis
    container_name: redis

    restart: always
  nginx:
    image: nginx:stable-alpine
    container_name: nginx
    volumes:
      - ./nginx/defult.conf:/etc/nginx/conf.d/default.conf

    ports:
      - "8080:80"
    depends_on:
      - node_app

volumes:
  mongo_data:
  postgres-db:
